apiVersion: v1
kind: Service
metadata:
  name: coupled-services-example1
  labels:
    app.kubernetes.io/instance: coupled-services-example1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: coupled-services-example1
