images:
  - name: example-java-springboot-webapp-placeholder
    newName: kimae09/example-java-springboot-webapp
    newTag: 0.0.4-SNAPSHOT # {"$imagepolicy": "tenant-app:example-java-springboot-webapp:tag"}