apiVersion : apps/v1
kind: Deployment
metadata:
  name: "example-java-springboot-webapp"
  labels:
    app.kubernetes.io/instance: example-java-springboot-webapp
    com.kimae/owner: lian
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-java-springboot-webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-java-springboot-webapp
    spec:
      securityContext:
        fsGroup: 41808
      containers:
        - name: app
          image: example-java-springboot-webapp-placeholder
          resources:
            limits:
              cpu: 1
              memory: 512M
            requests:
              memory: 512M
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: metrics
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: metrics
              scheme: HTTP
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsUser: 41808
            runAsGroup: 41808
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          volumeMounts:
            - mountPath: /tmp
              name: temp
            - mountPath: /app/config
              name: application-config
          envFrom:
            - configMapRef:
                name: example-java-springboot-webapp-env-vars
          env:
            - name: SOME_ENV_VAR
              value: "blabla"
      volumes:
        - name: temp
          emptyDir: {}
        - name: application-config
          configMap:
            name: example-java-springboot-webapp-files