apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-java-springboot-webapp
spec:
  imageRepositoryRef:
    name: example-java-springboot-webapp
  filterTags:
    pattern: "^(?P<version>[0-9]+.[0-9]+.[0-9]+)-SNAPSHOT$"
    extract: "version"
  policy:
    alphabetical:
      order: asc
